name: C CI

on:
  push:
    branches: [ "github" ]
  pull_request:
    branches: [ "github" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make
    - name: test
      run: ./cc TEST.c
